#!/usr/bin/bash

THEME_DIR=$1

# Set the wallpaper
killall swaybg
swaybg -m fill -i $THEME_DIR/wallpaper/pine-trees-black.jpg &

# Enabe the dunst notification daemon
killall dunst
dunst -config $THEME_DIR/dunst/dunstrc &

# Set the kitty terminal theme
# INFO: this destroys your old kitty config
mkdir -p ~/.config/kitty/themes
cp $THEME_DIR/kitty/kitty.conf ~/.config/kitty/kitty.conf
cp $THEME_DIR/kitty/Austere.conf ~/.config/kitty/themes/
kitty +kitten themes --reload-in=all "Austere"

# Set the rofi theme
# INFO: this destroys your old rofi config
mkdir -p ~/.config/rofi/themes
cp $THEME_DIR/rofi/austere.rasi ~/.config/rofi/themes/
cp $THEME_DIR/rofi/config.rasi ~/.config/rofi/config.rasi

# Set the swaylock theme
# INFO: this destroys your old swaylock config
unlink ~/.config/swaylock 2> /dev/null || rm -rf ~/.config/swaylock/
cp -r $THEME_DIR/swaylock ~/.config/swaylock

# Set the waybar theme
killall waybar
waybar -c $THEME_DIR/waybar/config.jsonc -s $THEME_DIR/waybar/style.css &

# Set the wlogout theme to
# INFO: this destroys your old wlogout config
unlink ~/.config/wlogout 2> /dev/null || rm -rf ~/.config/wlogout/
cp -r $THEME_DIR/wlogout ~/.config/wlogout

# Set GTK theme
gsettings set org.gnome.desktop.interface gtk-theme "Graphite-Dark"
gsettings set org.gnome.desktop.interface icon-theme "Tela-circle-black-dark"
