#!/usr/bin/bash

THEME_DIR=$1

# Set the wallpaper
swaybg -m fill -i $THEME_DIR/wallpaper/pine-trees-black.jpg &

# Enabe the dunst notification daemon
killall dunst
dunst -config $THEME_DIR/dunst/dunstrc &

# Set up autoname
kill -9 $(pgrep -f hyprland-autoname-workspaces)
hyprland-autoname-workspaces -c $THEME_DIR/hyprland-autoname-workspaces/config.toml &

# Set the kitty terminal theme
# INFO: this destroys your old kitty config
mkdir -p ~/.config/kitty/themes
cp $THEME_DIR/kitty/kitty.conf ~/.config/kitty/kitty.conf
kitty +kitten themes --reload-in=all "N0tch2k"

# Set the rofi theme
# INFO: this destroys your old rofi config
mkdir -p ~/.config/rofi/themes
cp $THEME_DIR/rofi/n0tch2k.rasi ~/.config/rofi/themes/
cp $THEME_DIR/rofi/config.rasi ~/.config/rofi/config.rasi

# Set the swaylock theme
# INFO: this destroys your old swaylock config
unlink ~/.config/swaylock 2> /dev/null || rm -rf ~/.config/swaylock/
cp -r $THEME_DIR/swaylock ~/.config/swaylock

# Set the waybar theme
# unlink ~/.local/bin/wttr-in.py 2> /dev/null || rm -rf ~/.local/bin/wttr-in.py
# ln -s $THEME_DIR/waybar/wttr-in.py ~/.local/bin/wttr-in.py
# unlink ~/.local/bin/todo-tui.py 2> /dev/null || rm -rf ~/.local/bin/todo-tui.py
# ln -s $THEME_DIR/waybar/todo-tui.py ~/.local/bin/todo-tui.py
# waybar -c $THEME_DIR/waybar/config.jsonc -s $THEME_DIR/waybar/style.css &

# Set the wlogout theme to
# INFO: this destroys your old wlogout config
unlink ~/.config/wlogout 2> /dev/null || rm -rf ~/.config/wlogout/
cp -r $THEME_DIR/wlogout ~/.config/wlogout
